apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 2
  selector:
    matchLabels:
       env: production
#    matchExpressions:
#      - { key: env,  operator: In,  values: [ production ] }
  template:
    metadata:
     name: kadam
     labels:
       env: production
    spec:
      containers:
      - name: con-pod1
        image: vimal13/apache-webserver-php